language: php
php:
      - '7.1'
      - '7.2'
      - '7.3'
      - '7.4'
      - '8.0'
before_script:
      - php -r 'if (version_compare(PHP_VERSION, "7.4.0") >= 0) echo exec("pecl install ffi"), PHP_EOL;'
      - php -r 'if (version_compare(PHP_VERSION, "7.2.0") >= 0) echo exec("wget https://github.com/swoole/swoole-src/archive/v4.6.0.tar.gz"), PHP_EOL; else echo exec("wget https://github.com/swoole/swoole-src/archive/v4.5.4.tar.gz"), PHP_EOL;'
      - php -r 'if (version_compare(PHP_VERSION, "7.2.0") >= 0) echo exec("tar -zxvf v4.6.0.tar.gz"), PHP_EOL; else echo exec("tar -zxvf v4.5.4.tar.gz"), PHP_EOL;'
      - php -r 'if (version_compare(PHP_VERSION, "7.2.0") >= 0) echo exec("mv swoole-src-4.6.0 swoole-src"), PHP_EOL; else echo exec("mv swoole-src-4.5.4 swoole-src"), PHP_EOL;'
      - cd swoole-src
      - phpize
      - ./configure
      - make -j 2
      - make install
      - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - cd ..
      - wget http://pecl.php.net/get/redis-5.3.4.tgz
      - tar -zxvf redis-5.3.4.tgz
      - cd redis-5.3.4
      - phpize
      - ./configure
      - make -j 2
      - make install
      - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - cd ..
      - composer install -vvv
script: ./vendor/bin/phpunit tests