language: php
php:
      - '7.1'
      - '7.2'
      - '7.3'
      - '7.4'
      - '8.0'
before_script:
      - php -r '(version_compare(PHP_VERSION, "7.4.0") >= 0) ? exec("pecl install ffi") : true;'
      - php -r '(version_compare(PHP_VERSION, "7.2.0") >= 0) ? exec("wget https://github.com/swoole/swoole-src/archive/v4.6.0.tar.gz") : exec("wget https://github.com/swoole/swoole-src/archive/v4.5.4.tar.gz");'
      - php -r '(version_compare(PHP_VERSION, "7.2.0") >= 0) ? exec("tar -zxvf v4.6.0.tar.gz") : exec("tar -zxvf v4.5.4.tar.gz");'
      - php -r '(version_compare(PHP_VERSION, "7.2.0") >= 0) ? exec("mv swoole-src-4.6.0 swoole-src") : exec("mv swoole-src-4.5.4 swoole-src");'
      - cd swoole-src
      - phpize
      - ./configure
      - make -j 2
      - make install
      - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - cd ..
      - wget http://pecl.php.net/get/redis-4.0.0.tgz
      - tar -zxvf redis-4.0.0.tgz
      - cd redis-4.0.0
      - phpize
      - ./configure
      - make -j 2
      - make install
      - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - cd ..
      - composer install -vvv
script: ./vendor/bin/phpunit tests