version: '3'

services:
  sw-fw-less:
    image: luoxiaojun1992/sw-fw-less:latest
    #       build: ./
    ports:
    - "9501:9501"
    volumes:
    - ./:/var/www/sw-fw-less
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["php", "/var/www/sw-fw-less/start.php"]